on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: Windows i686

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.84.0
        with:
          targets: i686-pc-windows-msvc

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build --target i686-pc-windows-msvc
